### ISSUE TITLE
running install.sh getting Failed

### ISSUE THREAD

**Issue by saquibansari0101** [bukunmialuko/flutter_ui_kit_obkm#99]
I have been trying to run the install.sh on my pc but I am facing this issue. I am using windows on my machine.

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

**Comment by bukunmialuko** [comment]
Delete pubspec.lock or run the latest code in main.
